# Generated by Django 6.0.5 on 2026-09-17 09:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('track', models.CharField(max_length=120)),
                ('slug', models.SlugField(blank=True, max_length=180, unique=True)),
                ('base_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('early_bird_fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('registration_start', models.DateTimeField()),
                ('registration_end', models.DateTimeField()),
                ('syllabus', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=12)),
                ('whatsapp_url', models.URLField(blank=True)),
                ('orientation_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=160)),
                ('email', models.EmailField(max_length=254)),
                ('whatsapp_number', models.CharField(max_length=24)),
                ('amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('paystack_reference', models.CharField(blank=True, max_length=120, null=True, unique=True)),
                ('payment_status', models.CharField(default='pending', max_length=20)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('whatsapp_invite_sent', models.BooleanField(default=False)),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='academy.cohort')),
            ],
            options={
                'ordering': ('-registration_date',),
            },
        ),
    ]
