# Generated by Django 6.0.5 on 2026-09-17 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='max_capacity',
            field=models.PositiveIntegerField(default=50),
        ),
    ]
